name: Deploy with Gradle

on:
  push:
    branches:
      - "master"
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and deploy with Gradle
        run: ./gradlew clean build publish
        env:
          ORG_GRADLE_PROJECT_n3fsUsername: ${{ secrets.REPOSILITE_USERNAME }}
          ORG_GRADLE_PROJECT_n3fsPassword: ${{ secrets.REPOSILITE_PASSWORD }}
      - name: Archive artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: "Build artifacts"
          path: "build/libs/gchat-velocity-*-all.jar"
          if-no-files-found: error
